/**
 * SQLite database setup — generated by WebToApp
 * Uses better-sqlite3 for synchronous, zero-config local storage.
 */
const Database = require('better-sqlite3');
const path = require('path');
const fs = require('fs');

let db;

function getDbPath() {
  // In Electron, store in userData. In dev, use local .data/ folder.
  if (process.versions.electron) {
    const { app } = require('electron');
    return path.join(app.getPath('userData'), 'database.db');
  }
  const dataDir = path.join(__dirname, '../.data');
  fs.mkdirSync(dataDir, { recursive: true });
  return path.join(dataDir, 'database.db');
}

function initDatabase() {
  const dbPath = getDbPath();
  db = new Database(dbPath);

  // Enable WAL mode for better concurrent read performance
  db.pragma('journal_mode = WAL');
  db.pragma('foreign_keys = ON');

  // Create tables
  // No tables detected — add your CREATE TABLE statements here

  console.log('[WebToApp] Database ready at', dbPath);
  return db;
}

function getDb() {
  if (!db) throw new Error('Database not initialised — call initDatabase() first');
  return db;
}

module.exports = { initDatabase, getDb };
