/**
 * Local Express backend — generated by WebToApp
 * Replaces cloud backend (Supabase/Firebase) with local SQLite + REST API
 */
const express = require('express');
const cors = require('cors');
const path = require('path');
const { initDatabase } = require('./database.cjs');
const authRouter = require('./auth.cjs');


const app = express();
const PORT = process.env.PORT || 3001;

// Middleware
app.use(cors({ origin: ['http://localhost:5173', 'http://localhost:3000', 'file://'] }));
app.use(express.json({ limit: '50mb' }));
app.use(express.urlencoded({ extended: true }));

// Serve local storage files
app.use('/storage', express.static(path.join(__dirname, 'storage')));

// Auth routes
app.use('/api/auth', authRouter);

// Table routes


// Health check
app.get('/api/health', (_req, res) => res.json({ status: 'ok', app: 'Pharmacy Tracker' }));

// 404 handler
app.use((_req, res) => res.status(404).json({ error: 'Not found' }));

// Error handler
app.use((err, _req, res, _next) => {
  console.error(err);
  res.status(500).json({ error: err.message ?? 'Internal server error' });
});

// Start
async function start() {
  await initDatabase();
  app.listen(PORT, '127.0.0.1', () => {
    console.log(`[WebToApp backend] Listening on http://127.0.0.1:${PORT}`);
  });
}

start().catch((err) => {
  console.error('Failed to start backend:', err);
  process.exit(1);
});
