import type { SourceFile } from "ts-morph";
import { BaseTransformer, type TransformContext, type TransformResult } from "../base/BaseTransformer.js";

/**
 * Rewrites Supabase Auth calls to local JWT auth backed by the
 * Express server and SQLite users table generated by WebToApp.
 *
 * Handles:
 *   supabase.auth.signInWithPassword({ email, password })
 *   supabase.auth.signUp({ email, password })
 *   supabase.auth.signOut()
 *   supabase.auth.getSession()
 *   supabase.auth.getUser()
 *   supabase.auth.onAuthStateChange(callback)
 *   useSession() / useUser() hooks
 */
export class SupabaseAuthTransformer extends BaseTransformer {

  canTransform(content: string): boolean {
    return (
      content.includes("supabase.auth") ||
      content.includes("onAuthStateChange") ||
      content.includes("useSession") ||
      content.includes("useSupabaseClient")
    );
  }

  protected async transformSourceFile(
    sourceFile: SourceFile,
    ctx: TransformContext
  ): Promise<Pick<TransformResult, "changes" | "warnings" | "confidence">> {
    const changes: string[] = [];
    const warnings: string[] = [];
    let confidence = 0.88;

    let text = sourceFile.getFullText();

    // ── Remove Supabase auth imports ───────────────────────────────
    text = text.replace(
      /import\s*\{[^}]*\}\s*from\s*['"]@supabase\/[^'"]+['"]\s*;?\n?/g,
      ""
    );

    // Add local auth import
    if (!text.includes("localAuth")) {
      text = `import { localAuth } from '@/lib/localAuth';\n` + text;
      changes.push("Added localAuth import");
    }

    // ── signInWithPassword ─────────────────────────────────────────
    text = text.replace(
      /await\s+supabase\.auth\.signInWithPassword\s*\(\s*\{([^}]+)\}\s*\)/g,
      (_match, body) => {
        changes.push("Rewrote signInWithPassword");
        return `await localAuth.signIn({${body}})`;
      }
    );

    // ── signUp ─────────────────────────────────────────────────────
    text = text.replace(
      /await\s+supabase\.auth\.signUp\s*\(\s*\{([^}]+)\}\s*\)/g,
      (_match, body) => {
        changes.push("Rewrote signUp");
        return `await localAuth.signUp({${body}})`;
      }
    );

    // ── signOut ────────────────────────────────────────────────────
    text = text.replace(
      /await\s+supabase\.auth\.signOut\s*\(\s*\)/g,
      () => {
        changes.push("Rewrote signOut");
        return `localAuth.signOut()`;
      }
    );

    // ── getSession ─────────────────────────────────────────────────
    text = text.replace(
      /await\s+supabase\.auth\.getSession\s*\(\s*\)/g,
      () => {
        changes.push("Rewrote getSession");
        return `localAuth.getSession()`;
      }
    );

    // ── getUser ────────────────────────────────────────────────────
    text = text.replace(
      /await\s+supabase\.auth\.getUser\s*\(\s*\)/g,
      () => {
        changes.push("Rewrote getUser");
        return `localAuth.getUser()`;
      }
    );

    // ── onAuthStateChange ──────────────────────────────────────────
    // This is trickier — Supabase returns a subscription object.
    // We replace it with a localAuth event listener.
    text = text.replace(
      /supabase\.auth\.onAuthStateChange\s*\(([^)]+)\)/g,
      (_match, callback) => {
        changes.push("Rewrote onAuthStateChange");
        warnings.push(
          "onAuthStateChange was rewritten to localAuth.onAuthChange. " +
            "The subscription.unsubscribe() pattern still works."
        );
        return `localAuth.onAuthChange(${callback})`;
      }
    );

    // ── useSession hook ────────────────────────────────────────────
    text = text.replace(
      /\buseSession\s*\(\s*\)/g,
      () => {
        changes.push("Rewrote useSession() hook");
        return `localAuth.useSession()`;
      }
    );

    // ── OAuth / social providers (warn + stub) ─────────────────────
    if (text.includes("signInWithOAuth") || text.includes("signInWithMagicLink")) {
      text = text.replace(
        /await\s+supabase\.auth\.signInWithOAuth\s*\([^)]+\)/g,
        `/* WebToApp: OAuth removed — use email/password */ localAuth.signIn({ email: '', password: '' })`
      );
      text = text.replace(
        /await\s+supabase\.auth\.signInWithMagicLink\s*\([^)]+\)/g,
        `/* WebToApp: Magic link removed — use email/password */ localAuth.signIn({ email: '', password: '' })`
      );
      warnings.push(
        "OAuth / magic link sign-in replaced with a stub. " +
          "Update the sign-in UI to use email/password."
      );
      confidence -= 0.15;
    }

    // ── Remove remaining supabase.auth references ──────────────────
    const remaining = (text.match(/supabase\.auth\./g) ?? []).length;
    if (remaining > 0) {
      warnings.push(
        `${remaining} remaining supabase.auth reference(s) not automatically handled. ` +
          "Review these manually."
      );
      confidence -= Math.min(remaining * 0.05, 0.2);
    }

    if (changes.length > 0) {
      sourceFile.replaceWithText(text);
    }

    return { changes, warnings, confidence: Math.max(confidence, 0.4) };
  }
}
