import type { SourceFile } from "ts-morph";
import { BaseTransformer, type TransformContext, type TransformResult } from "../base/BaseTransformer.js";

/**
 * Rewrites Supabase database query calls to equivalent calls against
 * the local Express REST API generated by WebToApp.
 *
 * Handles:
 *   supabase.from('table').select(...)       → GET  /api/table
 *   supabase.from('table').insert(...)       → POST /api/table
 *   supabase.from('table').update(...).eq()  → PUT  /api/table/:id
 *   supabase.from('table').delete().eq()     → DELETE /api/table/:id
 *   supabase.from('table').upsert(...)       → POST /api/table/upsert
 *
 * The generated localApi helper (produced by LocalApiGenerator) provides
 * a `localApi` object that mirrors the Supabase client query interface.
 */
export class SupabaseQueryTransformer extends BaseTransformer {

  canTransform(content: string): boolean {
    return (
      content.includes("@supabase/supabase-js") ||
      content.includes("supabase.from(") ||
      content.includes(".from(") && content.includes("supabase")
    );
  }

  protected async transformSourceFile(
    sourceFile: SourceFile,
    ctx: TransformContext
  ): Promise<Pick<TransformResult, "changes" | "warnings" | "confidence">> {
    const changes: string[] = [];
    const warnings: string[] = [];
    let confidence = 0.9;

    // ── 1. Remove / replace the supabase import ────────────────────
    this.removeSupabaseImport(sourceFile, changes);

    // ── 2. Replace supabase client instantiation ───────────────────
    this.replaceClientCreation(sourceFile, ctx, changes);

    // ── 3. Rewrite query chains ────────────────────────────────────
    const queryReplacements = this.rewriteQueryChains(sourceFile, ctx, warnings);
    changes.push(...queryReplacements.changes);
    confidence = Math.min(confidence, queryReplacements.confidence);

    // ── 4. Remove env var references ──────────────────────────────
    this.removeEnvVars(sourceFile, changes);

    return { changes, warnings, confidence };
  }

  // ─── Step 1: Remove supabase import ──────────────────────────────────────

  private removeSupabaseImport(sourceFile: SourceFile, changes: string[]): void {
    const supabaseImport = sourceFile.getImportDeclaration(
      (d) => d.getModuleSpecifierValue().includes("supabase")
    );
    if (!supabaseImport) return;

    supabaseImport.remove();
    this.addImport(sourceFile, "@/lib/localApi", ["localApi"]);
    changes.push("Replaced @supabase/supabase-js import with localApi");
  }

  // ─── Step 2: Replace createClient() ──────────────────────────────────────

  private replaceClientCreation(
    sourceFile: SourceFile,
    ctx: TransformContext,
    changes: string[]
  ): void {
    const count = this.replaceText(
      sourceFile,
      /const\s+supabase\s*=\s*createClient\s*\([^)]*\)/g,
      `// Supabase client replaced by WebToApp local API\n// const supabase = createClient(...) — removed`
    );
    if (count > 0) changes.push("Removed Supabase createClient() call");
  }

  // ─── Step 3: Rewrite query chains ────────────────────────────────────────

  private rewriteQueryChains(
    sourceFile: SourceFile,
    ctx: TransformContext,
    warnings: string[]
  ): { changes: string[]; confidence: number } {
    const changes: string[] = [];
    let confidence = 0.9;
    let text = sourceFile.getFullText();

    // ── SELECT ─────────────────────────────────────────────────────
    // supabase.from('table').select('*')
    // → await localApi.from('table').select()
    text = text.replace(
      /supabase\.from\s*\(\s*(['"`])(\w+)\1\s*\)\s*\.select\s*\([^)]*\)/g,
      (_match, _q, table) => {
        changes.push(`Rewrote SELECT on '${table}'`);
        return `await localApi.from('${table}').select()`;
      }
    );

    // ── SELECT with .eq() filter ───────────────────────────────────
    // supabase.from('table').select('*').eq('col', val)
    // → await localApi.from('table').select().eq('col', val)
    text = text.replace(
      /supabase\.from\s*\(\s*(['"`])(\w+)\1\s*\)\s*\.select\s*\([^)]*\)\s*\.eq\s*\(([^)]+)\)/g,
      (_match, _q, table, args) => {
        changes.push(`Rewrote SELECT+eq on '${table}'`);
        return `await localApi.from('${table}').select().eq(${args})`;
      }
    );

    // ── SELECT single row (.single()) ──────────────────────────────
    text = text.replace(
      /supabase\.from\s*\(\s*(['"`])(\w+)\1\s*\)\s*\.select\s*\([^)]*\)\s*(?:\.eq\s*\([^)]+\)\s*)?\.single\s*\(\s*\)/g,
      (_match, _q, table) => {
        changes.push(`Rewrote SELECT .single() on '${table}'`);
        return `await localApi.from('${table}').select().single()`;
      }
    );

    // ── INSERT ─────────────────────────────────────────────────────
    // supabase.from('table').insert({ ... })
    // → await localApi.from('table').insert({ ... })
    text = text.replace(
      /supabase\.from\s*\(\s*(['"`])(\w+)\1\s*\)\s*\.insert\s*\(([^;]+?)\)(?:\s*\.select\s*\([^)]*\))?/g,
      (_match, _q, table, data) => {
        changes.push(`Rewrote INSERT on '${table}'`);
        return `await localApi.from('${table}').insert(${data.trim()})`;
      }
    );

    // ── UPDATE ─────────────────────────────────────────────────────
    // supabase.from('table').update({ ... }).eq('id', val)
    // → await localApi.from('table').update({ ... }).eq('id', val)
    text = text.replace(
      /supabase\.from\s*\(\s*(['"`])(\w+)\1\s*\)\s*\.update\s*\(([^;]+?)\)\s*\.eq\s*\(([^)]+)\)/g,
      (_match, _q, table, data, eqArgs) => {
        changes.push(`Rewrote UPDATE on '${table}'`);
        return `await localApi.from('${table}').update(${data.trim()}).eq(${eqArgs})`;
      }
    );

    // ── DELETE ─────────────────────────────────────────────────────
    // supabase.from('table').delete().eq('id', val)
    // → await localApi.from('table').delete().eq('id', val)
    text = text.replace(
      /supabase\.from\s*\(\s*(['"`])(\w+)\1\s*\)\s*\.delete\s*\(\s*\)\s*\.eq\s*\(([^)]+)\)/g,
      (_match, _q, table, eqArgs) => {
        changes.push(`Rewrote DELETE on '${table}'`);
        return `await localApi.from('${table}').delete().eq(${eqArgs})`;
      }
    );

    // ── UPSERT ─────────────────────────────────────────────────────
    text = text.replace(
      /supabase\.from\s*\(\s*(['"`])(\w+)\1\s*\)\s*\.upsert\s*\(([^;]+?)\)/g,
      (_match, _q, table, data) => {
        changes.push(`Rewrote UPSERT on '${table}'`);
        return `await localApi.from('${table}').upsert(${data.trim()})`;
      }
    );

    // ── Error pattern: { data, error } destructuring ───────────────
    // Supabase returns { data, error } — localApi mirrors this so no change needed.
    // Just flag remaining raw supabase references as warnings.
    const remainingSupabase = (text.match(/\bsupabase\./g) ?? []).length;
    if (remainingSupabase > 0) {
      warnings.push(
        `${remainingSupabase} remaining 'supabase.' reference(s) could not be automatically transformed. ` +
          "These may use advanced query patterns (.rpc, .filter, .or, etc.) — check the AI fallback output."
      );
      confidence -= Math.min(remainingSupabase * 0.05, 0.3);
    }

    if (changes.length > 0) {
      sourceFile.replaceWithText(text);
    }

    return { changes, confidence };
  }

  // ─── Step 4: Remove env vars ──────────────────────────────────────────────

  private removeEnvVars(sourceFile: SourceFile, changes: string[]): void {
    const count = this.replaceText(
      sourceFile,
      /(?:import\.meta\.env|process\.env)\.\w*SUPABASE\w*/g,
      "undefined /* removed by WebToApp */"
    );
    if (count > 0) changes.push(`Removed ${count} Supabase env var reference(s)`);
  }
}
