import type { SourceFile } from "ts-morph";
import { BaseTransformer, type TransformContext, type TransformResult } from "../base/BaseTransformer.js";

/**
 * Rewrites Supabase Storage calls to the local file storage API
 * generated by WebToApp (Express + local filesystem).
 *
 * Supabase Storage:
 *   supabase.storage.from('bucket').upload(path, file)
 *   supabase.storage.from('bucket').download(path)
 *   supabase.storage.from('bucket').getPublicUrl(path)
 *   supabase.storage.from('bucket').remove([path])
 *   supabase.storage.from('bucket').list(folder)
 *
 * WebToApp replacement:
 *   localApi.storage.from('bucket').upload(path, file)   → POST /api/storage/:bucket
 *   localApi.storage.from('bucket').download(path)       → GET  /api/storage/:bucket/:path
 *   localApi.storage.from('bucket').getPublicUrl(path)   → returns local file URL
 *   localApi.storage.from('bucket').remove([path])       → DELETE /api/storage/:bucket/:path
 *   localApi.storage.from('bucket').list(folder)         → GET /api/storage/:bucket
 *
 * Files are stored in the Electron app's userData directory under /storage/
 */
export class SupabaseStorageTransformer extends BaseTransformer {

  canTransform(content: string): boolean {
    return (
      content.includes("supabase.storage") ||
      content.includes(".storage.from(") ||
      (content.includes("storage") && content.includes("supabase"))
    );
  }

  protected async transformSourceFile(
    sourceFile: SourceFile,
    ctx: TransformContext
  ): Promise<Pick<TransformResult, "changes" | "warnings" | "confidence">> {
    const changes: string[] = [];
    const warnings: string[] = [];
    let confidence = 0.85;

    // ── 1. Replace import ──────────────────────────────────────────
    this.removeSupabaseImport(sourceFile, changes);

    // ── 2. Rewrite storage calls ───────────────────────────────────
    const result = this.rewriteStorageCalls(sourceFile, warnings);
    changes.push(...result.changes);
    confidence = Math.min(confidence, result.confidence);

    return { changes, warnings, confidence };
  }

  private removeSupabaseImport(sourceFile: SourceFile, changes: string[]): void {
    const imp = sourceFile.getImportDeclaration(
      (d) => d.getModuleSpecifierValue().includes("supabase")
    );
    if (imp) {
      imp.remove();
      this.addImport(sourceFile, "@/lib/localApi", ["localApi"]);
      changes.push("Replaced @supabase/supabase-js import with localApi");
    }
  }

  private rewriteStorageCalls(
    sourceFile: SourceFile,
    warnings: string[]
  ): { changes: string[]; confidence: number } {
    const changes: string[] = [];
    let confidence = 0.85;
    let text = sourceFile.getFullText();

    // ── upload ─────────────────────────────────────────────────────
    // supabase.storage.from('bucket').upload(filePath, file, options?)
    text = text.replace(
      /supabase\.storage\.from\s*\(\s*(['"``])([\w-]+)\1\s*\)\s*\.upload\s*\(([^;)]+)\)/g,
      (_match, _q, bucket, args) => {
        changes.push(`Rewrote storage.upload() on bucket '${bucket}'`);
        return `await localApi.storage.from('${bucket}').upload(${args})`;
      }
    );

    // ── download ───────────────────────────────────────────────────
    text = text.replace(
      /supabase\.storage\.from\s*\(\s*(['"``])([\w-]+)\1\s*\)\s*\.download\s*\(([^)]+)\)/g,
      (_match, _q, bucket, args) => {
        changes.push(`Rewrote storage.download() on bucket '${bucket}'`);
        return `await localApi.storage.from('${bucket}').download(${args})`;
      }
    );

    // ── getPublicUrl ───────────────────────────────────────────────
    // Note: not async — returns { data: { publicUrl } }
    text = text.replace(
      /supabase\.storage\.from\s*\(\s*(['"``])([\w-]+)\1\s*\)\s*\.getPublicUrl\s*\(([^)]+)\)/g,
      (_match, _q, bucket, args) => {
        changes.push(`Rewrote storage.getPublicUrl() on bucket '${bucket}'`);
        return `localApi.storage.from('${bucket}').getPublicUrl(${args})`;
      }
    );

    // ── remove ─────────────────────────────────────────────────────
    text = text.replace(
      /supabase\.storage\.from\s*\(\s*(['"``])([\w-]+)\1\s*\)\s*\.remove\s*\(([^)]+)\)/g,
      (_match, _q, bucket, args) => {
        changes.push(`Rewrote storage.remove() on bucket '${bucket}'`);
        return `await localApi.storage.from('${bucket}').remove(${args})`;
      }
    );

    // ── list ───────────────────────────────────────────────────────
    text = text.replace(
      /supabase\.storage\.from\s*\(\s*(['"``])([\w-]+)\1\s*\)\s*\.list\s*\(([^)]*)\)/g,
      (_match, _q, bucket, args) => {
        changes.push(`Rewrote storage.list() on bucket '${bucket}'`);
        return `await localApi.storage.from('${bucket}').list(${args})`;
      }
    );

    // ── Warn on remaining storage references ───────────────────────
    const remaining = (text.match(/supabase\.storage/g) ?? []).length;
    if (remaining > 0) {
      warnings.push(
        `${remaining} storage reference(s) could not be automatically transformed. ` +
          "Check for .createSignedUrl(), .move(), or .copy() calls — use the AI fallback."
      );
      confidence -= remaining * 0.08;
    }

    if (changes.length > 0) {
      sourceFile.replaceWithText(text);
    }

    return { changes, confidence: Math.max(confidence, 0.4) };
  }
}
